# Generated by Django 5.2.16 on 2026-07-17 10:03

import apps.common.validators
import apps.preferences.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('color_vision_mode', models.CharField(choices=[('standard', 'Standard'), ('protanopia', 'Protanopie'), ('deuteranopia', 'Deuteranopie'), ('tritanopia', 'Tritanopie'), ('monochrome', 'Monochrom')], default='standard', max_length=20)),
                ('neuro_mode', models.BooleanField(default=False)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('reduce_hover', models.BooleanField(default=False)),
                ('magnifier', models.BooleanField(default=False)),
                ('font_size', models.CharField(choices=[('normal', 'Normal'), ('large', 'Groß'), ('xlarge', 'Sehr groß')], default='normal', max_length=12)),
                ('high_contrast', models.BooleanField(default=False)),
                ('dynamic_new_columns', models.BooleanField(default=True)),
                ('tooltips_enabled', models.BooleanField(default=True)),
                ('allow_invites', models.BooleanField(default=True)),
                ('hide_real_name', models.BooleanField(default=False)),
                ('real_name', models.CharField(blank=True, default='', max_length=60, validators=[apps.common.validators.reject_control_characters])),
                ('nickname', models.CharField(blank=True, default='', max_length=60, validators=[apps.common.validators.reject_control_characters])),
                ('alarms', models.JSONField(default=apps.preferences.models.default_alarms)),
                ('pomodoro', models.BooleanField(default=False)),
                ('task_timer', models.BooleanField(default=False)),
                ('weather', models.BooleanField(default=False)),
                ('weather_location', models.CharField(blank=True, default='', max_length=120, validators=[apps.common.validators.reject_control_characters])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarlyActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=32)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carly_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'action', 'created_at'], name='carly_action_limit_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarlyState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('show_globally', models.BooleanField(default=True)),
                ('messages_enabled', models.BooleanField(default=True)),
                ('task_reactions_enabled', models.BooleanField(default=True)),
                ('auto_sleep', models.BooleanField(default=True)),
                ('reduce_animations', models.BooleanField(default=False)),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('affection', models.PositiveSmallIntegerField(default=50)),
                ('energy', models.PositiveSmallIntegerField(default=80)),
                ('satiety', models.PositiveSmallIntegerField(default=70)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('mood', models.CharField(choices=[('glücklich', 'Glücklich'), ('neugierig', 'Neugierig'), ('müde', 'Müde'), ('hungrig', 'Hungrig')], default='neugierig', max_length=16)),
                ('is_sleeping', models.BooleanField(default=False)),
                ('last_message', models.CharField(default='Carly ist bereit.', max_length=300, validators=[apps.common.validators.reject_control_characters])),
                ('position_x', models.FloatField(default=0.85)),
                ('last_productive_day', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carly_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('affection__lte', 100)), name='carly_affection_max'), models.CheckConstraint(condition=models.Q(('energy__lte', 100)), name='carly_energy_max'), models.CheckConstraint(condition=models.Q(('satiety__lte', 100)), name='carly_satiety_max'), models.CheckConstraint(condition=models.Q(('position_x__gte', 0.0), ('position_x__lte', 1.0)), name='carly_position_range')],
            },
        ),
    ]
