# Generated by Django 5.2.16 on 2026-07-17 10:03

import apps.common.validators
import apps.workspaces.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('kind', models.CharField(choices=[('personal', 'Persönlich'), ('project', 'Projekt')], max_length=16)),
                ('title', models.CharField(max_length=120, validators=[apps.common.validators.reject_control_characters])),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('title', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(1), apps.common.validators.reject_control_characters])),
                ('color', models.CharField(default='#6558d3', max_length=7, validators=[apps.common.validators.validate_hex_color])),
                ('position', models.PositiveIntegerField(default=0)),
                ('sort_mode', models.CharField(blank=True, default='', max_length=16)),
                ('is_fixed_position', models.BooleanField(default=False)),
                ('is_dynamic', models.BooleanField(default=False)),
                ('system_role', models.CharField(blank=True, choices=[('new-assigned', 'Neu zugewiesen'), ('pool-review', 'Pool-Prüfung')], default='', max_length=24)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='workspaces.board')),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2), apps.common.validators.reject_control_characters])),
                ('route_key', models.SlugField(max_length=140)),
                ('slug_label', models.CharField(max_length=24, validators=[django.core.validators.MinLengthValidator(2), apps.common.validators.reject_control_characters])),
                ('description', models.TextField(blank=True, max_length=2000, validators=[apps.common.validators.reject_control_characters])),
                ('color', models.CharField(default='#6558d3', max_length=7, validators=[apps.common.validators.validate_hex_color])),
                ('icon', models.CharField(default='folder_open', max_length=50, validators=[apps.common.validators.validate_material_icon])),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Abgeschlossen'), ('archived', 'Archiviert')], default='active', max_length=16)),
                ('started_at', models.DateField(default=django.utils.timezone.localdate)),
                ('due_at', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('allows_on_demand_tasks', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', 'name'),
            },
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='workspaces.project'),
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('collaborator', 'Mitwirkend')], max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='workspaces.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('role', 'user__display_name'),
            },
        ),
        migrations.CreateModel(
            name='ProjectPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='workspaces.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('title', models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(1), apps.common.validators.reject_control_characters])),
                ('is_done', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subtasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('title', models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(1), apps.common.validators.reject_control_characters])),
                ('description', models.TextField(blank=True, max_length=10000, validators=[apps.common.validators.reject_control_characters])),
                ('priority', models.CharField(choices=[('hoch', 'Hoch'), ('mittel', 'Mittel'), ('niedrig', 'Niedrig')], default='mittel', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_shared_pool', models.BooleanField(default=False)),
                ('requires_review', models.BooleanField(default=False)),
                ('review_hint', models.CharField(blank=True, default='', max_length=300, validators=[apps.common.validators.reject_control_characters])),
                ('created_outside_column', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspaces.board')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_tasks', to=settings.AUTH_USER_MODEL)),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workspaces.boardcolumn')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tasks', to='workspaces.task')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspaces.project')),
                ('source_subtask', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mirror_task', to='workspaces.subtask')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mirrored_tasks', to='workspaces.task')),
            ],
            options={
                'ordering': ('position', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='workspaces.task'),
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.workspaces.models.attachment_upload_path, validators=[apps.common.validators.validate_upload])),
                ('original_name', models.CharField(max_length=255, validators=[apps.common.validators.reject_control_characters])),
                ('mime_type', models.CharField(max_length=150)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workspaces.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('body', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(1), apps.common.validators.reject_control_characters])),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workspaces.task')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=300, validators=[apps.common.validators.reject_control_characters])),
                ('icon', models.CharField(max_length=50, validators=[apps.common.validators.validate_material_icon])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_history_entries', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workspaces.task')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskRecurrenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('schedule_type', models.CharField(choices=[('weekly_days', 'Wochentage'), ('interval_days', 'Tagesintervall'), ('monthly_day', 'Monatstag')], max_length=20)),
                ('start_date', models.DateField()),
                ('interval_value', models.PositiveSmallIntegerField(default=1)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_run_on', models.DateField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rule', to='workspaces.task')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2), apps.common.validators.reject_control_characters])),
                ('allow_invites', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='board',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='workspaces.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=60, validators=[apps.common.validators.reject_control_characters])),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('accepted', 'Angenommen'), ('revoked', 'Widerrufen'), ('expired', 'Abgelaufen')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_workspace_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_workspace_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='workspaces.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar_color', models.CharField(default='#6558d3', max_length=7, validators=[apps.common.validators.validate_hex_color])),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_workspace_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_join_requests', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('member', 'Mitglied')], default='member', max_length=16)),
                ('avatar_color', models.CharField(default='#6558d3', max_length=7, validators=[apps.common.validators.validate_hex_color])),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
            options={
                'ordering': ('user__display_name',),
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2), apps.common.validators.reject_control_characters])),
                ('trigger', models.CharField(choices=[('task.completed', 'Task abgeschlossen'), ('task.reopened', 'Task wieder geöffnet'), ('task.created', 'Task erstellt'), ('task.assigned', 'Task zugewiesen'), ('column.entered', 'Spalte betreten')], max_length=32)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='workspaces.board')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['board', 'trigger', 'is_active'], name='automation_trigger_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='boardcolumn',
            constraint=models.UniqueConstraint(fields=('board', 'position'), name='board_column_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='boardcolumn',
            constraint=models.UniqueConstraint(condition=models.Q(('system_role', ''), _negated=True), fields=('board', 'system_role'), name='board_column_system_role_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectparticipant',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='project_participant_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectpreference',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='project_preference_unique'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['task', 'position'], name='subtask_task_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrecurrencerule',
            index=models.Index(fields=['is_active', 'next_run_on'], name='recurrence_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskrecurrencerule',
            constraint=models.CheckConstraint(condition=models.Q(('interval_value__gte', 1), ('interval_value__lte', 365)), name='recurrence_interval_range'),
        ),
        migrations.AddConstraint(
            model_name='taskrecurrencerule',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_month__isnull', True), models.Q(('day_of_month__gte', 1), ('day_of_month__lte', 31)), _connector='OR'), name='recurrence_month_day_range'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='workspace_owner_name_unique'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['board', 'column', 'position'], name='task_board_column_pos_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'assignee', 'is_done'], name='task_assignee_done_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'due_date'], name='task_project_due_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'archived_at'], name='task_archive_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('start_date__isnull', True), ('due_date__gte', models.F('start_date')), _connector='OR'), name='task_due_after_start'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'status'], name='project_workspace_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'due_at'], name='project_workspace_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('workspace', 'route_key'), name='project_route_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('due_at__gte', models.F('started_at'))), name='project_due_after_start'),
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'personal'), ('owner__isnull', False), ('project__isnull', True)), models.Q(('kind', 'project'), ('owner__isnull', True), ('project__isnull', False)), _connector='OR'), name='board_kind_target_consistent'),
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'personal')), fields=('workspace', 'owner'), name='personal_board_per_workspace_user'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvitation',
            index=models.Index(fields=['workspace', 'status'], name='invitation_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacejoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('workspace', 'user'), name='pending_join_request_unique'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['workspace', 'role'], name='workspace_member_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='workspace_membership_unique'),
        ),
    ]
